(define x 10000)
(define f 
    (lambda () 
        (lambda ()
            (lambda ()
                (lambda ()
                    (lambda ()
                        (lambda () 
                            (lambda () 
                                (lambda ()
                                    (lambda ()
                                        (lambda ()
                                            (lambda () x
                                            )
                                        )
                                    )
                                )
                            )
                        )
                    )
                )
            )
        )
    )
)

(define main (lambda (n) (if (> (((((((((((f))))))))))) n) (main (+ n 1)) 5)))
(main 0)